# Do not edit this file directly! Instead, override any variables you want to
# override by defining them in config.mk.

# Prefix directory other variables are based on (if not set expclitly)
PREFIX=/usr/local

# Directory where odpdown-init will end up
BINDIR=${PREFIX}/bin

# Directory where makefiles/ will end up
DATADIR=${PREFIX}/share/odpdown-tools

# Directory where the content of themes/ will end up
THEMEDIR=${DATADIR}/themes
