# Do not edit this file directly! Instead, override any variables you want to
# override by defining them in config.mk.

# Prefix directory other variables are based on (if not set expclitly)
PREFIX=/usr/local

# Directory where odpdown-init will end up
BINDIR=${PREFIX}/bin

# Directory where odpdown-init will look for makefiles/
DATADIR=${PREFIX}/share/odpdown-tools
# Directory where makefiles/ will actually end up (useful for packagers)
INSTALL_DATADIR=${DATADIR}

# Directory where odpdown-init will look for themes/
THEMEDIR=${DATADIR}/themes
# Directory where themes/ will actually end up (useful for packagers)
INSTALL_THEMEDIR=${THEMEDIR}
